import { Shipment } from "./types";

export const DATA: Shipment[] = [
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"MSC",date:"2025-07-16"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"Napoles",line:"MSC",date:"2025-07-16"},
  {client:"Naturkost",incoterm:"FOB",fcl:40,weight:20,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"Hamburg",line:"ONE",date:"2025-07-22"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"MSC",date:"2025-07-24"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"MSC",date:"2025-07-25"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"MSC",date:"2025-08-04"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"MSC",date:"2025-08-05"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"MSC",date:"2025-08-08"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"MSC",date:"2025-08-08"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"Italy",line:"MSC",date:"2025-08-18"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"MSC",date:"2025-08-21"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"MSC",date:"2025-08-21"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"MSC",date:"2025-08-21"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"MSC",date:"2025-08-22"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"MSC",date:"2025-08-22"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"MSC",date:"2025-08-22"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"MSC",date:"2025-08-25"},
  {client:"Abbott",incoterm:"FOB",fcl:20,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Oakland",line:"ONE",date:"2025-08-25"},
  {client:"Abbott",incoterm:"FOB",fcl:20,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Oakland",line:"ONE",date:"2025-08-26"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"MSC",date:"2025-08-27"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"MSC",date:"2025-08-27"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"MSC",date:"2025-08-29"},
  {client:"Scalzo",incoterm:"FOB",fcl:20,weight:20,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"Melbourne",line:"MSC",date:"2025-08-28"},
  {client:"Scalzo",incoterm:"FOB",fcl:20,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Melbourne",line:"MSC",date:"2025-08-28"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"MSC",date:"2025-09-01"},
  {client:"Smirk",incoterm:"FOB",fcl:20,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Oakland",line:"MSC",date:"2025-09-10"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"ORGANIC BLACK CHIA SEEDS",pod:"Hamburg",line:"MSC",date:"2025-09-15"},
  {client:"Smirk",incoterm:"FOB",fcl:20,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"New York",line:"Hapag",date:"2025-09-19"},
  {client:"Unicorn",incoterm:"FOB",fcl:20,weight:20,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"MSC",date:"2025-09-24"},
  {client:"Better Body Foods",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Los Angeles",line:"MAERSK",date:"2025-09-25"},
  {client:"Better Body Foods",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Los Angeles",line:"MAERSK",date:"2025-09-25"},
  {client:"Bewital",incoterm:"FOB",fcl:40,weight:24,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"Hamburg",line:"MSC",date:"2025-09-25"},
  {client:"Unicorn",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Hamburg",line:"Hapag",date:"2025-09-26"},
  {client:"NSI",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Kansas",line:"Maersk",date:"2025-10-06"},
  {client:"NSI",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Kansas",line:"Maersk",date:"2025-10-06"},
  {client:"NSI",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Kansas",line:"Maersk",date:"2025-10-06"},
  {client:"NSI",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Kansas",line:"Maersk",date:"2025-10-07"},
  {client:"NSI",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Kansas",line:"Maersk",date:"2025-10-07"},
  {client:"Abbott",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Oakland",line:"ONE",date:"2025-10-08"},
  {client:"Abbott",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Oakland",line:"ONE",date:"2025-10-08"},
  {client:"Abbott",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Newark",line:"MAERSK",date:"2025-10-08"},
  {client:"Abbott",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Newark",line:"MAERSK",date:"2025-10-08"},
  {client:"Better Body Foods",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Los Angeles",line:"MAERSK",date:"2025-10-09"},
  {client:"Better Body Foods",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Los Angeles",line:"MAERSK",date:"2025-10-09"},
  {client:"NSI",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Kansas",line:"Maersk",date:"2025-10-10"},
  {client:"NSI",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Kansas",line:"Maersk",date:"2025-10-10"},
  {client:"NSI",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Kansas",line:"Maersk",date:"2025-10-13"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"ORGANIC BLACK CHIA SEEDS",pod:"Hamburg",line:"MSC",date:"2025-10-10"},
  {client:"Sesajal",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Houston, TX",line:"Maersk",date:"2025-10-13"},
  {client:"Smirks",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Oakland",line:"ONE",date:"2025-10-17"},
  {client:"Smirks",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Oakland",line:"ONE",date:"2025-10-17"},
  {client:"NSI",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Kansas",line:"Maersk",date:"2025-10-17"},
  {client:"NSI",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Kansas",line:"Maersk",date:"2025-10-18"},
  {client:"Smirks",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Newark",line:"Maersk",date:"2025-10-18"},
  {client:"Smirks",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Newark",line:"Maersk",date:"2025-10-18"},
  {client:"NSI",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Kansas",line:"Maersk",date:"2025-10-18"},
  {client:"NSI",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Kansas",line:"Maersk",date:"2025-10-18"},
  {client:"Smirks",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Oakland",line:"ONE",date:"2025-10-21"},
  {client:"Tradin Org",incoterm:"FOB",fcl:40,weight:24,product:"ORGANIC BLACK CHIA SEEDS",pod:"Rotterdam",line:"MSC",date:"2025-10-23"},
  {client:"NSI",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Kansas",line:"Maersk",date:"2025-10-23"},
  {client:"NSI",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Kansas",line:"Maersk",date:"2025-10-23"},
  {client:"NSI",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Kansas",line:"Maersk",date:"2025-10-24"},
  {client:"NSI",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Kansas",line:"Maersk",date:"2025-10-25"},
  {client:"NSI",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Kansas",line:"Maersk",date:"2025-10-25"},
  {client:"NSI",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Kansas",line:"Maersk",date:"2025-10-25"},
  {client:"Sesajal",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Houston, TX",line:"Maersk",date:"2025-10-28"},
  {client:"Sesajal",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Houston, TX",line:"Maersk",date:"2025-10-28"},
  {client:"Sesajal",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Houston, TX",line:"Maersk",date:"2025-10-29"},
  {client:"Sesajal",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Houston, TX",line:"Maersk",date:"2025-10-29"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:20,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"Rotterdam",line:"MSC",date:"2025-11-05"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"Hapag",date:"2025-11-05"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"Hapag",date:"2025-11-05"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"Hapag",date:"2025-11-06"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"Hapag",date:"2025-11-06"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"MSC",date:"2025-11-06"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"MSC",date:"2025-11-06"},
  {client:"Scalzo",incoterm:"FOB",fcl:20,weight:20,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"Melbourne",line:"CMA",date:"2025-11-07"},
  {client:"Clean Plate",incoterm:"CIF",fcl:40,weight:20,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"Miami",line:"Maersk",date:"2025-11-07"},
  {client:"Tradin Org",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Rotterdam",line:"MSC",date:"2025-11-07"},
  {client:"Rhumveld",incoterm:"FOB",fcl:40,weight:25,product:"ORGANIC BLACK CHIA SEEDS",pod:"Rotterdam",line:"GRIM",date:"2025-11-07"},
  {client:"Rhumveld",incoterm:"FOB",fcl:40,weight:25,product:"ORGANIC BLACK CHIA SEEDS",pod:"Rotterdam",line:"GRIM",date:"2025-11-07"},
  {client:"Rhumveld",incoterm:"FOB",fcl:40,weight:25,product:"ORGANIC BLACK CHIA SEEDS",pod:"Rotterdam",line:"GRIM",date:"2025-11-08"},
  {client:"Rhumveld",incoterm:"FOB",fcl:40,weight:25,product:"ORGANIC BLACK CHIA SEEDS",pod:"Rotterdam",line:"GRIM",date:"2025-11-08"},
  {client:"Do it",incoterm:"FOB",fcl:20,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Rotterdam",line:"GRIM",date:"2025-11-13"},
  {client:"Do it",incoterm:"FOB",fcl:20,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Rotterdam",line:"GRIM",date:"2025-11-13"},
  {client:"Smirks",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Newark",line:"MAERSK",date:"2025-11-19"},
  {client:"Smirks",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Oakland",line:"ONE",date:"2025-11-19"},
  {client:"Smirks",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Oakland",line:"ONE",date:"2025-11-19"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"MSC",date:"2025-11-20"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"MSC",date:"2025-11-20"},
  {client:"Abbott",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Oakland",line:"ONE",date:"2025-11-21"},
  {client:"Abbott",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Oakland",line:"ONE",date:"2025-11-21"},
  {client:"Abbott",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Newark",line:"Maersk",date:"2025-11-21"},
  {client:"Abbott",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Newark",line:"Maersk",date:"2025-11-21"},
  {client:"Do it",incoterm:"FOB",fcl:20,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Rotterdam",line:"MSC",date:"2025-11-24"},
  {client:"Do it",incoterm:"FOB",fcl:20,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Rotterdam",line:"MSC",date:"2025-11-24"},
  {client:"Do it",incoterm:"FOB",fcl:20,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Rotterdam",line:"MSC",date:"2025-11-24"},
  {client:"Smirks",incoterm:"CFR",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Oakland",line:"ONE",date:"2025-11-25"},
  {client:"Smirks",incoterm:"CFR",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Oakland",line:"ONE",date:"2025-11-25"},
  {client:"Sesajal",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Houston, TX",line:"Maersk",date:"2025-11-26"},
  {client:"Sesajal",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Houston, TX",line:"Maersk",date:"2025-11-26"},
  {client:"Sesajal",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Houston, TX",line:"Maersk",date:"2025-11-26"},
  {client:"Better Body Foods",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Los Angeles",line:"MAERSK",date:"2025-11-27"},
  {client:"Sesajal",incoterm:"CFR",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Houston, TX",line:"MAERSK",date:"2025-12-03"},
  {client:"Abbott",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Oakland",line:"ONE",date:"2025-12-10"},
  {client:"Better Body Foods",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Los Angeles",line:"MAERSK",date:"2025-12-11"},
  {client:"Abbott",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Oakland",line:"ONE",date:"2025-12-11"},
  {client:"NSI",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Kansas",line:"Maersk",date:"2025-12-11"},
  {client:"NSI",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Kansas",line:"Maersk",date:"2025-12-11"},
  {client:"Sesajal",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Houston, TX",line:"Maersk",date:"2025-12-12"},
  {client:"Sesajal",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Houston, TX",line:"Maersk",date:"2025-12-12"},
  {client:"Sesajal",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Houston, TX",line:"Maersk",date:"2025-12-12"},
  {client:"NSI",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Kansas",line:"Maersk",date:"2025-12-12"},
  {client:"NSI",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Kansas",line:"Maersk",date:"2025-12-12"},
  {client:"Midsona",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Hamburg",line:"MSC",date:"2025-12-15"},
  {client:"NSI",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Kansas",line:"Maersk",date:"2025-12-16"},
  {client:"NSI",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Kansas",line:"Maersk",date:"2025-12-16"},
  {client:"NSI",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Kansas",line:"Maersk",date:"2025-12-16"},
  {client:"Do it",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Rotterdam",line:"MSC",date:"2025-12-17"},
  {client:"Do it",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Rotterdam",line:"MSC",date:"2025-12-17"},
  {client:"Royal",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Rotterdam",line:"CMA",date:"2025-12-17"},
  {client:"Royal",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Rotterdam",line:"CMA",date:"2025-12-17"},
  {client:"Sesajal",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Houston, TX",line:"Maersk",date:"2025-12-18"},
  {client:"Sesajal",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Houston, TX",line:"Maersk",date:"2025-12-18"},
  {client:"Sesajal",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Houston, TX",line:"Maersk",date:"2025-12-18"},
  {client:"Seneca",incoterm:"CFR",fcl:40,weight:20,product:"PET",pod:"Charleston",line:"Maersk",date:"2025-12-18"},
  {client:"Midsona",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Hamburg",line:"MSC",date:"2025-12-19"},
  {client:"Midsona",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Hamburg",line:"MSC",date:"2025-12-19"},
  {client:"Midsona",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Hamburg",line:"MSC",date:"2025-12-19"},
  {client:"Midsona",incoterm:"FOB",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Hamburg",line:"MSC",date:"2025-12-19"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:20,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"MSC",date:"2025-12-20"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"MSC",date:"2025-12-20"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"MSC",date:"2025-12-20"},
  {client:"Olam",incoterm:"CFR",fcl:20,weight:12.5,product:"ORGANIC BLACK CHIA SEEDS",pod:"Singapore",line:"CMA",date:"2025-12-20"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"MSC",date:"2025-12-20"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"MSC",date:"2025-12-20"},
  {client:"Voicevale",incoterm:"FOB",fcl:40,weight:25,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"MSC",date:"2025-12-22"},
  {client:"Red River",incoterm:"CFR",fcl:20,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Rotterdam",line:"MSC",date:"2025-12-22"},
  {client:"Red River",incoterm:"CFR",fcl:40,weight:20,product:"ORGANIC BLACK CHIA SEEDS",pod:"Rotterdam",line:"MSC",date:"2025-12-22"},
  {client:"Rhumveld",incoterm:"FOB",fcl:40,weight:20,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"Rotterdam",line:"MSC",date:"2025-12-23"},
  {client:"Rhumveld",incoterm:"FOB",fcl:40,weight:20,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"MSC",date:"2025-12-23"},
  {client:"AFI Impex Peru",incoterm:"CFR",fcl:40,weight:27,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"Peru",line:"ZIM",date:"2025-12-23"},
  {client:"Community Foods",incoterm:"CFR",fcl:40,weight:20,product:"BULK CHIA SEEDS BLACK CONVENTIONAL",pod:"London",line:"HAPAG",date:"2025-12-23"},
];
